version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-app
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
